'use-strict'
export const CHECK_INTERNET_CONNECTION = 'CHECK_INTERNET_CONNECTION';
export const APP_LANG = 'APP_LANG';
export const CART_ITEMS = 'CART_ITEMS';
export const TOTAL_CART_ITEMS = 'TOTAL_CART_ITEMS';
export const TOTAL_TAX_ITEMS = 'TOTAL_TAX_ITEMS';
export const ALL_COUNTRIES = 'ALL_COUNTRIES';

export const TOTAL_CART_ITEMS_AMOUNT = 'TOTAL_CART_ITEMS_AMOUNT';
export const DELETE_SHIPPING_AND_BILLING = 'DELETE_SHIPPING_AND_BILLING'

export const SAVE_RELATED_SEARCH = 'SAVE_RELATED_SEARCH'
export const REMOVE_RELATED_SEARCH = 'REMOVE_RELATED_SEARCH'
export const SAVE_WISHLIST_DATA = 'SAVE_WISHLIST_DATA'
export const SAVE_CATEGORY_DATA = 'SAVE_CATEGORY_DATA'
export const SAVE_ORDERS_DATA = 'SAVE_ORDERS_DATA'
export const SAVE_WALLET_DATA = 'SAVE_WALLET_DATA'
export const SAVE_USAGE_WALLET_DATA = 'SAVE_USAGE_WALLET_DATA'
export const SAVE__WALLET_AMONT_USER = 'SAVE__WALLET_AMONT_USER'
export const SAVE_ARASCA_PHONE = 'SAVE_ARASCA_PHONE'
export const SAVE_ARASCA_EMAIL = 'SAVE_ARASCA_EMAIL'


export const SAVE_RECENTLY_PURDATA = 'SAVE_RECENTLY_PURDATA'
export const SET_USER_TOKEN = 'SET_USER_TOKEN'
export const SET_USER_PASS = 'SET_USER_PASS'

export const SET_USER_TOKEN_ADMIN = 'SET_USER_TOKEN_ADMIN'
export const SET_USER_NOTIFICATION = 'SET_USER_NOTIFICATION'
export const SET_USER_UNREAD_NOTIFICATION = 'SET_USER_UNREAD_NOTIFICATION'

export const SET_USER_SHIPPING = 'SET_USER_SHIPPING'
export const SET_USER_BILLING = 'SET_USER_BILLING'
export const SAVE_ALL_COUPONS = 'SAVE_ALL_COUPONS'



export const SHOW_SLIDER = 'SHOW_SLIDER';
export const SAVE_GUEST_ID = 'SAVE_GUEST_ID';

export const NOTI_FCM_ID = 'NOTI_FCM_ID';
export const SET_DEFAULT_LANGUAGE = "SET_DEFAULT_LANGUAGE";
export const SIGNUP_REWARDS_SUCCESS = "SIGNUP_REWARDS_SUCCESS";

export const SET_LOGGED_USER_DATA = 'SET_LOGGED_USER_DATA';
export const SET_LOGGED_USER_PASSWORD = 'SET_LOGGED_USER_PASSWORD';
export const SET_VISIBLE = 'SET_VISIBLE';
export const SET_MAIN_CATEGORIES = 'SET_MAIN_CATEGORIES';
export const SET_MY_PROFILE_DATA = 'SET_MY_PROFILE_DATA';
export const SET_NEAREST_PAGE_LISTING = 'SET_NEAREST_PAGE_LISTING';
export const UPDATE_NEAREST_PAGE_LISTING = 'UPDATE_NEAREST_PAGE_LISTING';
export const SET_NEAREST_PAGE_NUMBER = 'SET_NEAREST_PAGE_NUMBER';
export const UPDATE_BUSINESS_FOLLOW = 'UPDATE_BUSINESS_FOLLOW';
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_WISHLIST = "GET_WISHLIST";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const CLEAR_ALL_WISHLIST = "CLEAR_ALL_WISHLIST";
export const REMOVE_TO_WISHLIST = "REMOVE_TO_WISHLIST";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_TO_CART = "REMOVE_TO_CART";

export const SAVE_QUESTIONARY = "SAVE_QUESTIONARY";
export const GET_QUESTIONARY = "GET_QUESTIONARY";

export const SET_EVENT_SUCCESSFULLY = "SET_EVENT_SUCCESSFULLY";

export const SAVE_FILTER_SUCCESS = "SAVE_FILTER_SUCCESS"
export const APPLY_FILTER_SUCCESS = "APPLY_FILTER_SUCCESS"
export const RESET_FILTER_SUCCESS = "RESET_FILTER_SUCCESS"
export const SORT_BY_SUCCESS = "SORT_BY_SUCCESS"
export const UPDATE_QUANTITY = "UPDATE_QUANTITY"
export const UPDATE_SIZE = "UPDATE_SIZE"
export const GET_TOP3_PRODUCTS = "GET_TOP3_PRODUCTS"
export const CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS"
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS"
export const UPDATE_CART_WRAPPING = "UPDATE_CART_WRAPPING"
export const REMOVE_CART_WRAPPING = "REMOVE_CART_WRAPPING"
export const UPDATE_WISHLIST_ICON = "UPDATE_WISHLIST_ICON"

//Types for Appstate 
export const FOREGROUND = 'APP_STATE.FOREGROUND';
export const BACKGROUND = 'APP_STATE.BACKGROUND';
export const INACTIVE = 'APP_STATE.INACTIVE';

//Orders
export const SAVE_BUSINESSMAN_ORDERS = 'SAVE_BUSINESSMAN_ORDERS';
export const SAVE_SALESMAN_ORDERS = 'SAVE_SALESMAN_ORDERS';

export const LOGIN_ACTION_TYPES = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
    LOGIN_REQUEST_FAIL: 'LOGIN_REQUEST_FAIL',
    LOGOUT_REQUEST_SUCCESS: 'LOGOUT_REQUEST_SUCCESS'
}




export const SIGNUP_ACTION_TYPES = {
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_REQUEST_SUCCESS: 'SIGNUP_REQUEST_SUCCESS',
    SIGNUP_REQUEST_FAIL: 'SIGNUP_REQUEST_FAIL',
    SIGNOUT_REQUEST_SUCCESS: 'SIGNOUT_REQUEST_SUCCESS'
}

export const VEHICLE_ACTION_TYPES = {
    VEHICLE_REQUEST: 'VEHICLE_REQUEST',
    VEHICLE_REQUEST_SUCCESS: 'VEHICLE_REQUEST_SUCCESS',
    VEHICLE_REQUEST_FAIL: 'VEHICLE_REQUEST_FAIL',
    VEHICLE_REQUEST_SUCCESS: 'VEHICLE_REQUEST_SUCCESS',
    APP_STEPID_REQUEST_SUCCESS: 'APP_STEPID_REQUEST_SUCCESS'
}
export const APP_STEPID_ACTION_TYPES = {
    APP_STEPID_REQUEST: 'APP_STEPID_REQUEST',
    APP_STEPID_REQUEST_SUCCESS: 'APP_STEPID_REQUEST_SUCCESS',
    APP_STEPID_REQUEST_FAIL: 'APP_STEPID_REQUEST_FAIL',
}




